# Generated by Django 4.2 on 2023-05-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='programme',
            field=models.CharField(blank=True, choices=[('Civil Engineering', 'Civil Engineering'), ('Computer Engineering', 'Computer Engineering'), ('Aerospace Engineering', 'Aerospace Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Petroleum Engineering', 'Petroleum Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Biomedical Engineering', 'Biomedical Engineering'), ('Petrochemical Engineering', 'Petrochemical Engineering'), ('Materials Engineering', 'Materials Engineering')], max_length=100, null=True),
        ),
    ]
