# Generated by Django 4.2 on 2023-05-10 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_allocation', '0005_alter_timetable_programme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='code',
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='room_allocation.paper'),
        ),
    ]
